# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import attack_pb2 as attack__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/attack.Greeter/SayHello',
                request_serializer=attack__pb2.HelloRequest.SerializeToString,
                response_deserializer=attack__pb2.HelloReply.FromString,
                )
        self.SayHelloStreamReply = channel.unary_stream(
                '/attack.Greeter/SayHelloStreamReply',
                request_serializer=attack__pb2.HelloRequest.SerializeToString,
                response_deserializer=attack__pb2.HelloReply.FromString,
                )
        self.SayReady = channel.unary_unary(
                '/attack.Greeter/SayReady',
                request_serializer=attack__pb2.ReadyRequest.SerializeToString,
                response_deserializer=attack__pb2.ReadyReply.FromString,
                )
        self.Position = channel.unary_unary(
                '/attack.Greeter/Position',
                request_serializer=attack__pb2.N.SerializeToString,
                response_deserializer=attack__pb2.SoldiersPosition.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloStreamReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayReady(self, request, context):
        """Modification-1 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Position(self, request, context):
        """Modification-2: Creating Soldiers Positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=attack__pb2.HelloRequest.FromString,
                    response_serializer=attack__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloStreamReply': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHelloStreamReply,
                    request_deserializer=attack__pb2.HelloRequest.FromString,
                    response_serializer=attack__pb2.HelloReply.SerializeToString,
            ),
            'SayReady': grpc.unary_unary_rpc_method_handler(
                    servicer.SayReady,
                    request_deserializer=attack__pb2.ReadyRequest.FromString,
                    response_serializer=attack__pb2.ReadyReply.SerializeToString,
            ),
            'Position': grpc.unary_unary_rpc_method_handler(
                    servicer.Position,
                    request_deserializer=attack__pb2.N.FromString,
                    response_serializer=attack__pb2.SoldiersPosition.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'attack.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/attack.Greeter/SayHello',
            attack__pb2.HelloRequest.SerializeToString,
            attack__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloStreamReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/attack.Greeter/SayHelloStreamReply',
            attack__pb2.HelloRequest.SerializeToString,
            attack__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/attack.Greeter/SayReady',
            attack__pb2.ReadyRequest.SerializeToString,
            attack__pb2.ReadyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Position(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/attack.Greeter/Position',
            attack__pb2.N.SerializeToString,
            attack__pb2.SoldiersPosition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
